version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Your existing Dockerfile that builds both client and server
    ports:
      - "3000:3000"  # Expose client port
      - "9000:9000"  # Expose server port
